### ISSUE TITLE
Switching boost mode on/off

### ISSUE THREAD

**Issue by sumnerboy12** [michaelarnauts/home-assistant-comfoconnect#18]
I have humidity sensors in my 2x bathrooms and would like to activate boost mode automatically when the sensors detect someone is having a shower.

I can see that `set_boost` is available in your [aiocomfoconnect](https://github.com/michaelarnauts/aiocomfoconnect) library, so would it be possible to add this as a switch to the HACs integration for controlling via automations?

Thanks for building and sharing this great component!

**Comment by michaelarnauts** [comment]
I haven't implemented boost in Home Assistant since boost uses the same fan speeds as level High. The only difference is that boost falls back after a specific time. You can do this yourself with an automation in Home Assistant.

**Comment by sumnerboy12** [comment]
Fair enough - thanks for sharing this!

**Comment by sumnerboy12** [comment]
I don't know this for a fact, but wouldn't it make it a lot easier to provide the boost function, it would mean you don't have to store the current state and then restore once your boost timer expires?

I.e. what if change my system to manual mode and set the fan on low. Then someone has a shower and I detect high humidity. I would need to store the current system mode and fan level somewhere, then set the fan to high, and after 10 mins (or the humidity drops) restore to the original settings.

Presumably with boost mode, this is all handled by the unit?

**Comment by michaelarnauts** [comment]
You could write a service so you can do this from Home Assistant. The library should support this already.

I have never done this before, more info is available here: https://developers.home-assistant.io/docs/dev_101_services

**Comment by r3st0r3** [comment]
After exposing set-boost via CLI in [aiocomfoconnect](https://github.com/michaelarnauts/aiocomfoconnect/pull/19/commits/6c80de2dfe3cdd2e62a1233957eab40d4f3b071b) wouldn't it make sense to also include boost-control directly in home-assistant-comfoconnect?
From my point of view it doesn't make any sense to develop something that is ready and working in the Zehnder ComfoOs again as HA-Service.

**Comment by szibis** [comment]
I think we don't need to replicate schedules or unit automation managed from app or unit itself. Why ?? because they don't have whole Home Assistant platform soo they just implement some basic automations in the app itself. 
In our case there is no problem to add automation  based on simple control we expose via https://github.com/michaelarnauts/aiocomfoconnect. We can setup any schedules or automation  for humidity control or for temperature control (bypass, comfocool) by having simple modes to on/off or use ventilation speeds before boost. Anything that we put in Home Assistant  can be easily override by unit or mobile app and I don't feel that we should apply here some super advance controls based on unit behaviours.
Even if unit overrides some behaviour still if HA has automation for example set low speed when when something than it will just apply and change unit behaviour. Still if unit has this settings to manage humidity it will try to force that automatically which is out of any control if on unit we have automatic control 
![IMG_0972](https://github.com/michaelarnauts/home-assistant-comfoconnect/assets/329831/7c067ac3-4d92-4a27-b917-c77f5da5df76)

**Comment by fritzrichter** [comment]
First of all thanks for this great enhancement, it's a much better integration then the original one. I actually would love to see the boost mode as well being added. Why? I do have a KNX system and the KNX bridge for the Zehnder System as well. In KNX I already have some logic which is attached to the boost mode being activated, for example the system activates the boost mode automatically in case the "House Party" mode is activated. That's all controlled by KNX. HA would just display that the party mode or in this case the boost mode is activated. As the underlaying lib supports it, why not adding a couple of lines to the source code? :) I could maybe look into it and provide a pull-request if you want?

Same actually applies for the away mode.

What I am missing is the RMOT value, which was available in the original integration, any chance to add this?

**Comment by ChrisMisker** [comment]
> I have humidity sensors in my 2x bathrooms and would like to activate boost mode automatically when the sensors detect someone is having a shower.
> 
> I can see that `set_boost` is available in your [aiocomfoconnect](https://github.com/michaelarnauts/aiocomfoconnect) library, so would it be possible to add this as a switch to the HACs integration for controlling via automations?
> 
> Thanks for building and sharing this great component!

Another thought here: what device do you have? ComfoAir Q? You can turn on moisture detection in your ComfoAir and it will go into higher ventilation mode when someone is showering automatically. This works quicker than a humidity sensor, because it takes some time for the whole bathroom to become humid.

**Comment by sumnerboy12** [comment]
> Another thought here: what device do you have? ComfoAir Q? You can turn on moisture detection in your ComfoAir and it will go into higher ventilation mode when someone is showering automatically. This works quicker than a humidity sensor, because it takes some time for the whole bathroom to become humid.

Can you share your settings for this?

I have mine set to Humidity Protection: Auto Only and Humidity Comfort: Off.

![Screenshot_20240715-124035.png](https://github.com/user-attachments/assets/ba75f612-8d81-4c94-88a8-aecf4e8aa476)

But I haven't noticed it kicking in by itself.

**Comment by ChrisMisker** [comment]
> > Another thought here: what device do you have? ComfoAir Q? You can turn on moisture detection in your ComfoAir and it will go into higher ventilation mode when someone is showering automatically. This works quicker than a humidity sensor, because it takes some time for the whole bathroom to become humid.
> 
> Can you share your settings for this?
> 
> I have mine set to Humidity Protection: Auto Only and Humidity Comfort: Off.
> 
> ![Screenshot_20240715-124035.png](https://github.com/user-attachments/assets/ba75f612-8d81-4c94-88a8-aecf4e8aa476)
> 
> But I haven't noticed it kicking in by itself. 
> 
> 

I have comfort humidity also on.

**Comment by sumnerboy12** [comment]
> I have comfort humidity also on.

Do you have it set to `ON` or `AUTO ONLY`?

**Comment by ChrisMisker** [comment]
> > I have comfort humidity also on.
> 
> 
> 
> Do you have it set to `ON` or `AUTO ONLY`?
> 
> 

Comfort is ON
The other 2 are Auto ONLY

**Comment by sumnerboy12** [comment]
I can confirm this is now working for me as well - thanks for the suggestion - much better than having an automation in HA!!
