### ISSUE TITLE
Failed to call service /fan 

### ISSUE THREAD

**Issue by wgumaa** [michaelarnauts/home-assistant-comfoconnect#48]
Recently I have noticed some strange behaviour. 

I am using a generic entity button for my ComfoAir Q .  When i click one of the fan speeds I get a 

![image](https://github.com/michaelarnauts/home-assistant-comfoconnect/assets/105917603/dbeaca67-52eb-464a-ba5a-0ef4cdc02e88)

Then it may work after a few seconds. 

Anyone else? Any ideas? 

The same when I try and change the percentage "Failed to call service fan/set_percentage. unknown error" 

Then after a few clicks it works.

**Comment by nonnynz** [comment]
I am experiencing this too. @michaelarnauts, I believe it could be related to the fix deployed for https://github.com/michaelarnauts/home-assistant-comfoconnect/issues/43. 

Before that fix, I experienced occasional connection drops to the bridge that would not resolve until a restart of Home Assistant.

After that fix, the connection becomes permanently unstable instead of dropping entirely, by constantly disconnecting from and reconnecting to the bridge. During this time, using any of functionality of this integration may fail as @wgumaa reported. As before, this can only be resolved be restarting Home Assistant.

You can see an example of this in the screenshot attached. This history chart plots the extract temperature of the Comfo unit. The data is smoothed by averaging, but you can see the time period where the connection to the bridge entered a permanent state of instability. This was eventually resolved by a restart of Home Assistant in the morning.

![IMG_8134](https://github.com/michaelarnauts/home-assistant-comfoconnect/assets/355644/51e66ee4-7e22-4b1b-bdca-12cc79824774)
