### ISSUE TITLE
Ventilation boost

### ISSUE THREAD

**Issue by atomic339** [michaelarnauts/home-assistant-comfoconnect#8]
Hi, 
This integration is great. Thanks you so much for your work. I have small request. Can you add boost mod for 30 minutes?

**Comment by Burtond** [comment]
I agree, this is a great integration, thank you so much.  I did review the aiocomfoconnect library and noticed that get_boost and set_boost were already methods you created in your library.  I'm no where near ready to develop HA integrations, but I too would find getting boost status to be very helpful.  I use a Shelly 1 connected to my boost option on my Q450, but when I initiate boost mode, I can't get the status.  It would be great have that feature.  Again, thank you for your efforts with this integration.

**Comment by mhu1987** [comment]
Personally, since i've started using HA, I dont use the ComfoControl app, and it's much easier to set the automation in HA to keep lvl 3 (same as boost) for like 15minutes or less/more depending on your automation

**Comment by michaelarnauts** [comment]
I'm currently not planning to expose boost mode (and away mode) in Home Assistant since the same could be achieved with an automation and setting the level to the maximum or the minimum for a specific amount of time. When boost mode is activated, the level will change in Home Assistant, so you should be able to detect it there.

It is available in the library however for people who want to control the ventilation unit without Home Assistant.
