### ISSUE TITLE
Energy consumption is not displayed correctly

### ISSUE THREAD

**Issue by DrZoidberg89** [michaelarnauts/home-assistant-comfoconnect#88]
Hello,

I have the problem that the energy consumption is not displayed correctly in the energy dashboard. 

It was always wrong before the update. It always added the consumption in 1kWh steps and then reduced it to show the correct consumption:
![Bildschirmfoto 2024-10-04 um 10 44 23](https://github.com/user-attachments/assets/7f1ed865-65ed-40b6-a0a4-0b7a631e78aa)
The only problem is that the tot
al usage of the appliances shows the consumption but not the deduction. In other words, the value is incorrect.

Now, after the new update, the whole thing is even worse because it shows me 169kWh but deducts 169.41kWh, which is actually a negative consumption. Which can't be right.

![Bildschirmfoto 2024-10-04 um 10 45 14](https://github.com/user-attachments/assets/a7dcc377-5fd4-4128-ae69-517c07a551dc)

Does anyone know the problem and how to fix it?

**Comment by michaelarnauts** [comment]
The problem is that the sensor is only showing increments of 1kWh, and your ventilation unit isn't using a kWh per day, so it only gets updated every few days.

A fix could be to use the integral integration and use the  real-time sensor.ventilation_power_usage to create a better total with increments every few seconds. This can then be added to the energy dashboard.

This is how I did this.

![Screenshot_20241004-164145](https://github.com/user-attachments/assets/fbc38984-eb7d-45c8-985b-617a4a724dcc)

**Comment by DrZoidberg89** [comment]
Hi @michaelarnauts ,

that's works fine for me.

Thank you very much.

**Comment by kroeckx** [comment]
I started using this too. I've noticed that if the source value doesn't change for a while, the integral value also doesn't change:
![Screenshot 2024-11-08 094417](https://github.com/user-attachments/assets/84a8896f-de98-4ec7-9d1c-38cce9ed3d47)

So I'm now trying with the "Max sub-interval" set to 1 minute instead of 0.

**Comment by kroeckx** [comment]
So things seem to be working fine for me now. 

An other thing I've noticed is that the comfoairq sometimes just doesn't count anymore. The integral seems to have the right slope, but the comfoairq counted 13 kWh while the integral counted 24 in the same time. When it's showing the 0 value, the comfoairq doesn't seem to be counting the energy.
