### ISSUE TITLE
Error HomeAssistant Core (2024.10.4) - Zehnder Comfoair Q 350 (2.3)

### ISSUE THREAD

**Issue by lcfsm** [michaelarnauts/home-assistant-comfoconnect#95]
Hello,
After installing the latest version of HomeAssistant Core (core_2024.10.4), the integration for the Zehnder Comfoair Q 350 (2.3) has stopped working.

![core](https://github.com/user-attachments/assets/61c25635-3bdf-47f0-8b29-85bcd4207758)

**Comment by bartwr** [comment]
Hi @lcfsm, since yesterday the issue that happened when updating to Home Assistant **2024.11** has been fixed. Update to [v0.3.0](https://github.com/michaelarnauts/home-assistant-comfoconnect/releases/tag/v0.3.0) to make `home-assistant-comfoconnect` work with Home Assistant 2024.11:

1. Open Home Assistant
2. Go to **HACS**
3. Search for **ComfoAir**
4. Click **Click Zehnder ComfoAirQ** in the search results
5. Click the 3 dots at the right top of the screen
6. Click "Re-download" (or similar) in the menu that appears

On your screen the modal now sais: "Version v0.3.0 will be downloaded". 

7. Click **Download**
8. Now restart Home Assistant

The integration should be working again.

**Comment by Obioban** [comment]
Excellent! Thanks for staying on top of this!

**Comment by ChrisMisker** [comment]
Are you using HACS 2.0, or the older HACS? (@bartwr )

**Comment by ChrisMisker** [comment]
After a bunch of restarting and redownloading , it seems the problem fixed itself.
